name: Scheduled Benchmark 3.2
on:
  schedule:
    - cron: '*/30 * * * *'
#    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write
jobs:
  benchmark-triple:
    name: benchmark-triple
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        id: checkout-dubbo-benchmark
        with:
          repository: 'icodening/dubbo-benchmark'
          ref: benchmark-proposal
          token: ${{ secrets.BENCHMARK }}
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
      #--------------------------------benchmark----------------------------------
      - name: Setup dubbo version
        run: |
          bash ./prepare.sh 3.2.11

      - name: Run benchmark for triple-server
        run: |
          bash ./benchmark.sh -m profiling dubbo-triple-server & sleep 60

      - name: Run benchmark for triple-client
        run: |
          bash ./benchmark.sh -m profiling dubbo-triple-client
      #--------------------------------benchmark----------------------------------

      - name: Checkout benchmark result
        run: |
          mkdir -p benchmark/dubbo-triple-client/3.2/ && mv *.json benchmark/dubbo-triple-client/3.2/
          mkdir -p profiling/dubbo-triple-client/3.2/ && mv dubbo-triple-client/*.jfr profiling/dubbo-triple-client/3.2/
          mkdir -p profiling/dubbo-triple-server/3.2/ && mv dubbo-triple-server/*.jfr profiling/dubbo-triple-server/3.2/
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout --orphan benchmark-result
          git fetch origin benchmark-result
          git rm -rf .
          git pull origin benchmark-result
          git add ./benchmark
          git add ./profiling
          git commit -m "Add benchmark result"

      - name: Push branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BENCHMARK }}  # 使用内置的 PERSONAL TOKEN 授权
          branch: benchmark-result
          repository: icodening/dubbo-benchmark

#  benchmark-dubbo:
#    name: benchmark-dubbo
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        id: checkout-dubbo-benchmark
#        with:
#          repository: 'icodening/dubbo-benchmark'
#          ref: benchmark-proposal
#          token: ${{ secrets.BENCHMARK }}
#      - uses: actions/setup-java@v3
#        with:
#          java-version: '8'
#          distribution: 'zulu'
#      #--------------------------------benchmark----------------------------------
#      - name: Setup dubbo version
#        run: |
#          bash ./prepare.sh 3.2.11
#
#      - name: Run benchmark for dubbo-fastjson2-server
#        run: |
#          bash ./benchmark.sh dubbo-fastjson2-server & sleep 60
#
#      - name: Run benchmark for dubbo-fastjson2-client
#        run: |
#          bash ./benchmark.sh -a -benchmarkName=dubbo-fastjson2-3.2 dubbo-fastjson2-client
#
#      #--------------------------------benchmark----------------------------------
#
#      - name: Checkout benchmark result
#        run: |
#          git config --global user.email "actions@github.com"
#          git config --global user.name "GitHub Actions"
#          git checkout --orphan benchmark-result
#          git fetch origin benchmark-result
#          git rm -rf .
#          git pull origin benchmark-result
#          git add ./dubbo-fastjson2-3.2
#          git commit -m "Add benchmark result"
#
#      - name: Push branch
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.BENCHMARK }}  # 使用内置的 PERSONAL TOKEN 授权
#          branch: benchmark-result
#          repository: icodening/dubbo-benchmark

